/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.r3chain.data.api.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.r3chain.data.api.apis.AuthApi
import io.r3chain.data.api.models.AuthLoginRequestDto
import io.r3chain.data.api.models.AuthResponseEntity
import io.r3chain.data.api.models.AuthSaveRequestDto
import io.r3chain.data.api.models.GeneralResponseEntity

class AuthApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AuthApi
        //val apiInstance = AuthApi()

        // to test apiV1AuthLoginPost
        should("test apiV1AuthLoginPost") {
            // uncomment below to test apiV1AuthLoginPost
            //val authLoginRequestDto : AuthLoginRequestDto =  // AuthLoginRequestDto | 
            //val result : AuthResponseEntity = apiInstance.apiV1AuthLoginPost(authLoginRequestDto)
            //result shouldBe ("TODO")
        }

        // to test apiV1AuthLogoutPost
        should("test apiV1AuthLogoutPost") {
            // uncomment below to test apiV1AuthLogoutPost
            //val result : GeneralResponseEntity = apiInstance.apiV1AuthLogoutPost()
            //result shouldBe ("TODO")
        }

        // to test apiV1AuthSavePost
        should("test apiV1AuthSavePost") {
            // uncomment below to test apiV1AuthSavePost
            //val authSaveRequestDto : AuthSaveRequestDto =  // AuthSaveRequestDto | 
            //val result : AuthResponseEntity = apiInstance.apiV1AuthSavePost(authSaveRequestDto)
            //result shouldBe ("TODO")
        }

        // to test apiV1AuthVerifyPost
        should("test apiV1AuthVerifyPost") {
            // uncomment below to test apiV1AuthVerifyPost
            //val result : GeneralResponseEntity = apiInstance.apiV1AuthVerifyPost()
            //result shouldBe ("TODO")
        }

    }
}
