/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.r3chain.data.api.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.r3chain.data.api.apis.FacilityApi
import io.r3chain.data.api.models.FacilityListRequestDto
import io.r3chain.data.api.models.FacilityResponseEntity
import io.r3chain.data.api.models.FacilitySaveRequestDto

class FacilityApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of FacilityApi
        //val apiInstance = FacilityApi()

        // to test apiV1FacilityListPost
        should("test apiV1FacilityListPost") {
            // uncomment below to test apiV1FacilityListPost
            //val facilityListRequestDto : FacilityListRequestDto =  // FacilityListRequestDto | 
            //val result : FacilityResponseEntity = apiInstance.apiV1FacilityListPost(facilityListRequestDto)
            //result shouldBe ("TODO")
        }

        // to test apiV1FacilitySavePost
        should("test apiV1FacilitySavePost") {
            // uncomment below to test apiV1FacilitySavePost
            //val facilitySaveRequestDto : FacilitySaveRequestDto =  // FacilitySaveRequestDto | 
            //val result : FacilityResponseEntity = apiInstance.apiV1FacilitySavePost(facilitySaveRequestDto)
            //result shouldBe ("TODO")
        }

    }
}
