/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.r3chain.data.api.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.r3chain.data.api.apis.LocationApi
import io.r3chain.data.api.models.LocationListRequestDto
import io.r3chain.data.api.models.LocationResponseEntity
import io.r3chain.data.api.models.LocationSaveRequestDto

class LocationApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of LocationApi
        //val apiInstance = LocationApi()

        // to test apiV1LocationListPost
        should("test apiV1LocationListPost") {
            // uncomment below to test apiV1LocationListPost
            //val locationListRequestDto : LocationListRequestDto =  // LocationListRequestDto | 
            //val result : LocationResponseEntity = apiInstance.apiV1LocationListPost(locationListRequestDto)
            //result shouldBe ("TODO")
        }

        // to test apiV1LocationSavePost
        should("test apiV1LocationSavePost") {
            // uncomment below to test apiV1LocationSavePost
            //val locationSaveRequestDto : LocationSaveRequestDto =  // LocationSaveRequestDto | 
            //val result : LocationResponseEntity = apiInstance.apiV1LocationSavePost(locationSaveRequestDto)
            //result shouldBe ("TODO")
        }

    }
}
