/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.r3chain.data.api.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.r3chain.data.api.apis.OrganizationUserApi
import io.r3chain.data.api.models.OrganizationUserResponseEntity
import io.r3chain.data.api.models.OrganizationUserSaveRequestDto

class OrganizationUserApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of OrganizationUserApi
        //val apiInstance = OrganizationUserApi()

        // to test apiV1UserListPost
        should("test apiV1UserListPost") {
            // uncomment below to test apiV1UserListPost
            //val body : kotlin.Any = Object // kotlin.Any | 
            //val result : OrganizationUserResponseEntity = apiInstance.apiV1UserListPost(body)
            //result shouldBe ("TODO")
        }

        // to test apiV1UserSavePost
        should("test apiV1UserSavePost") {
            // uncomment below to test apiV1UserSavePost
            //val organizationUserSaveRequestDto : OrganizationUserSaveRequestDto =  // OrganizationUserSaveRequestDto | 
            //val result : OrganizationUserResponseEntity = apiInstance.apiV1UserSavePost(organizationUserSaveRequestDto)
            //result shouldBe ("TODO")
        }

    }
}
