/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.r3chain.data.api.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.r3chain.data.api.apis.OrganizationApi
import io.r3chain.data.api.models.OrganizationResponseEntity
import io.r3chain.data.api.models.OrganizationSaveRequestDto

class OrganizationApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of OrganizationApi
        //val apiInstance = OrganizationApi()

        // to test apiV1OrganizationListPost
        should("test apiV1OrganizationListPost") {
            // uncomment below to test apiV1OrganizationListPost
            //val result : OrganizationResponseEntity = apiInstance.apiV1OrganizationListPost()
            //result shouldBe ("TODO")
        }

        // to test apiV1OrganizationSavePost
        should("test apiV1OrganizationSavePost") {
            // uncomment below to test apiV1OrganizationSavePost
            //val organizationSaveRequestDto : OrganizationSaveRequestDto =  // OrganizationSaveRequestDto | 
            //val result : OrganizationResponseEntity = apiInstance.apiV1OrganizationSavePost(organizationSaveRequestDto)
            //result shouldBe ("TODO")
        }

    }
}
