/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.r3chain.data.api.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.r3chain.data.api.apis.PartnerApi
import io.r3chain.data.api.models.PartnerListRequestDto
import io.r3chain.data.api.models.PartnerResponseEntity
import io.r3chain.data.api.models.PartnerSaveRequestDto

class PartnerApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PartnerApi
        //val apiInstance = PartnerApi()

        // to test apiV1PartnerListPost
        should("test apiV1PartnerListPost") {
            // uncomment below to test apiV1PartnerListPost
            //val partnerListRequestDto : PartnerListRequestDto =  // PartnerListRequestDto | 
            //val result : PartnerResponseEntity = apiInstance.apiV1PartnerListPost(partnerListRequestDto)
            //result shouldBe ("TODO")
        }

        // to test apiV1PartnerSavePost
        should("test apiV1PartnerSavePost") {
            // uncomment below to test apiV1PartnerSavePost
            //val partnerSaveRequestDto : PartnerSaveRequestDto =  // PartnerSaveRequestDto | 
            //val result : PartnerResponseEntity = apiInstance.apiV1PartnerSavePost(partnerSaveRequestDto)
            //result shouldBe ("TODO")
        }

    }
}
