/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.r3chain.data.api.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.r3chain.data.api.apis.ResourceApi
import io.r3chain.data.api.models.ResourceListRequestDto
import io.r3chain.data.api.models.ResourceResponseEntity
import io.r3chain.data.api.models.ResourceSaveRequestDto
import io.r3chain.data.api.models.ResourceUploadRequestDto
import io.r3chain.data.api.models.StringStringValuesKeyValuePair

class ResourceApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ResourceApi
        //val apiInstance = ResourceApi()

        // to test apiV1ResourceListPost
        should("test apiV1ResourceListPost") {
            // uncomment below to test apiV1ResourceListPost
            //val resourceListRequestDto : ResourceListRequestDto =  // ResourceListRequestDto | 
            //val result : ResourceResponseEntity = apiInstance.apiV1ResourceListPost(resourceListRequestDto)
            //result shouldBe ("TODO")
        }

        // to test apiV1ResourceSavePost
        should("test apiV1ResourceSavePost") {
            // uncomment below to test apiV1ResourceSavePost
            //val resourceSaveRequestDto : ResourceSaveRequestDto =  // ResourceSaveRequestDto | 
            //val result : ResourceResponseEntity = apiInstance.apiV1ResourceSavePost(resourceSaveRequestDto)
            //result shouldBe ("TODO")
        }

        // to test apiV1ResourceUploadPost
        should("test apiV1ResourceUploadPost") {
            // uncomment below to test apiV1ResourceUploadPost
            //val requestDto : ResourceUploadRequestDto =  // ResourceUploadRequestDto | 
            //val fileList : kotlin.collections.List<StringStringValuesKeyValuePair> =  // kotlin.collections.List<StringStringValuesKeyValuePair> | 
            //val result : ResourceResponseEntity = apiInstance.apiV1ResourceUploadPost(requestDto, fileList)
            //result shouldBe ("TODO")
        }

    }
}
