/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.r3chain.data.api.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.r3chain.data.api.apis.TraceApi
import io.r3chain.data.api.models.TraceListRequestDto
import io.r3chain.data.api.models.TraceResponseEntity

class TraceApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TraceApi
        //val apiInstance = TraceApi()

        // to test apiV1TraceListPost
        should("test apiV1TraceListPost") {
            // uncomment below to test apiV1TraceListPost
            //val traceListRequestDto : TraceListRequestDto =  // TraceListRequestDto | 
            //val result : TraceResponseEntity = apiInstance.apiV1TraceListPost(traceListRequestDto)
            //result shouldBe ("TODO")
        }

    }
}
