/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.r3chain.data.api.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.r3chain.data.api.apis.WasteRecordApi
import io.r3chain.data.api.models.WasteRecordListRequestDto
import io.r3chain.data.api.models.WasteRecordResponseEntity
import io.r3chain.data.api.models.WasteRecordSaveRequestDto

class WasteRecordApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of WasteRecordApi
        //val apiInstance = WasteRecordApi()

        // to test apiV1WasteRecordListPost
        should("test apiV1WasteRecordListPost") {
            // uncomment below to test apiV1WasteRecordListPost
            //val wasteRecordListRequestDto : WasteRecordListRequestDto =  // WasteRecordListRequestDto | 
            //val result : WasteRecordResponseEntity = apiInstance.apiV1WasteRecordListPost(wasteRecordListRequestDto)
            //result shouldBe ("TODO")
        }

        // to test apiV1WasteRecordSavePost
        should("test apiV1WasteRecordSavePost") {
            // uncomment below to test apiV1WasteRecordSavePost
            //val wasteRecordSaveRequestDto : WasteRecordSaveRequestDto =  // WasteRecordSaveRequestDto | 
            //val result : WasteRecordResponseEntity = apiInstance.apiV1WasteRecordSavePost(wasteRecordSaveRequestDto)
            //result shouldBe ("TODO")
        }

    }
}
