/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.r3chain.data.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * Values: OK,VALIDATION_ERROR,UNAUTHORIZED,PLACE_NOT_FOUND,FILE_NOT_FOUND,ONLY_ONE_PARTNER_TYPE_PER_WASTE_RECORD_SUPPORTED,NO_EDIT_FOR_ALREADY_PROCESSED_RECORDS,ONLY_ONE_PLASTIC_TYPE_SUPPORTED,WRONG_PARENT_WASTE_PLASTIC_RECORD_ID_LIST,NOT_ENOUGH_WEIGHT_OF_PLASTIC_TYPE_TO_DISPATCH,NOT_ENOUGH_WEIGHT_OF_PLASTIC_TYPE_TO_ADJUST,DO_NOT_UPDATE_PARTNER_TYPE,DO_NOT_UPDATE_WASTE_RECORD_STAGE,DO_NOT_UPDATE_WASTE_RECORD_TYPE,NOT_SUPPORTED_WASTE_RECORD_TYPE_FACILITY_TYPE_CONFIGURATION,NEED_SPECIFY_LINK_MODE,UNKNOWN_ERROR,NOT_SUPPORTED,NOT_ALLOWED_TO_CHANGE,FORBIDDEN
 */

@JsonClass(generateAdapter = false)
enum class ApiStatusCode(val value: kotlin.String) {

    @Json(name = "ok")
    OK("ok"),

    @Json(name = "validationError")
    VALIDATION_ERROR("validationError"),

    @Json(name = "unauthorized")
    UNAUTHORIZED("unauthorized"),

    @Json(name = "placeNotFound")
    PLACE_NOT_FOUND("placeNotFound"),

    @Json(name = "fileNotFound")
    FILE_NOT_FOUND("fileNotFound"),

    @Json(name = "onlyOnePartnerTypePerWasteRecordSupported")
    ONLY_ONE_PARTNER_TYPE_PER_WASTE_RECORD_SUPPORTED("onlyOnePartnerTypePerWasteRecordSupported"),

    @Json(name = "noEditForAlreadyProcessedRecords")
    NO_EDIT_FOR_ALREADY_PROCESSED_RECORDS("noEditForAlreadyProcessedRecords"),

    @Json(name = "onlyOnePlasticTypeSupported")
    ONLY_ONE_PLASTIC_TYPE_SUPPORTED("onlyOnePlasticTypeSupported"),

    @Json(name = "wrongParentWastePlasticRecordIDList")
    WRONG_PARENT_WASTE_PLASTIC_RECORD_ID_LIST("wrongParentWastePlasticRecordIDList"),

    @Json(name = "notEnoughWeightOfPlasticTypeToDispatch")
    NOT_ENOUGH_WEIGHT_OF_PLASTIC_TYPE_TO_DISPATCH("notEnoughWeightOfPlasticTypeToDispatch"),

    @Json(name = "notEnoughWeightOfPlasticTypeToAdjust")
    NOT_ENOUGH_WEIGHT_OF_PLASTIC_TYPE_TO_ADJUST("notEnoughWeightOfPlasticTypeToAdjust"),

    @Json(name = "doNotUpdatePartnerType")
    DO_NOT_UPDATE_PARTNER_TYPE("doNotUpdatePartnerType"),

    @Json(name = "doNotUpdateWasteRecordStage")
    DO_NOT_UPDATE_WASTE_RECORD_STAGE("doNotUpdateWasteRecordStage"),

    @Json(name = "doNotUpdateWasteRecordType")
    DO_NOT_UPDATE_WASTE_RECORD_TYPE("doNotUpdateWasteRecordType"),

    @Json(name = "notSupportedWasteRecordTypeFacilityTypeConfiguration")
    NOT_SUPPORTED_WASTE_RECORD_TYPE_FACILITY_TYPE_CONFIGURATION("notSupportedWasteRecordTypeFacilityTypeConfiguration"),

    @Json(name = "needSpecifyLinkMode")
    NEED_SPECIFY_LINK_MODE("needSpecifyLinkMode"),

    @Json(name = "unknownError")
    UNKNOWN_ERROR("unknownError"),

    @Json(name = "notSupported")
    NOT_SUPPORTED("notSupported"),

    @Json(name = "notAllowedToChange")
    NOT_ALLOWED_TO_CHANGE("notAllowedToChange"),

    @Json(name = "forbidden")
    FORBIDDEN("forbidden");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is ApiStatusCode) "$data" else null

        /**
         * Returns a valid [ApiStatusCode] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): ApiStatusCode? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

