/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.r3chain.data.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * Values: INDIVIDUAL_COLLECTOR,COLLECTION_POINT
 */

@JsonClass(generateAdapter = false)
enum class EnumPartnerInboundType(val value: kotlin.String) {

    @Json(name = "individualCollector")
    INDIVIDUAL_COLLECTOR("individualCollector"),

    @Json(name = "collectionPoint")
    COLLECTION_POINT("collectionPoint");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is EnumPartnerInboundType) "$data" else null

        /**
         * Returns a valid [EnumPartnerInboundType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): EnumPartnerInboundType? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

