/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.r3chain.data.api.models

import io.r3chain.data.api.models.EnumPlasticType

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param plasticTypeList 
 * @param netWeight 
 * @param grossWeight 
 * @param tareWeight 
 */


data class PlasticWeightDto (

    @Json(name = "plasticTypeList")
    val plasticTypeList: kotlin.collections.List<EnumPlasticType>? = null,

    @Json(name = "netWeight")
    val netWeight: kotlin.Double? = null,

    @Json(name = "grossWeight")
    val grossWeight: kotlin.Double? = null,

    @Json(name = "tareWeight")
    val tareWeight: kotlin.Double? = null

)

