/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.r3chain.data.api.models

import io.r3chain.data.api.models.EnumFileType

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param filePath 
 * @param fileType 
 * @param fileSize 
 * @param mimeType 
 * @param width 
 * @param height 
 * @param posterFilePath 
 * @param posterWidth 
 * @param posterHeight 
 * @param duration 
 * @param uiId 
 * @param latitude 
 * @param longitude 
 * @param at 
 * @param locationID 
 */


data class ResourceDto (

    @Json(name = "id")
    val id: kotlin.Int,

    @Json(name = "filePath")
    val filePath: kotlin.String,

    @Json(name = "fileType")
    val fileType: EnumFileType,

    @Json(name = "fileSize")
    val fileSize: kotlin.Int,

    @Json(name = "mimeType")
    val mimeType: kotlin.String,

    @Json(name = "width")
    val width: kotlin.Int,

    @Json(name = "height")
    val height: kotlin.Int,

    @Json(name = "posterFilePath")
    val posterFilePath: kotlin.String,

    @Json(name = "posterWidth")
    val posterWidth: kotlin.Int,

    @Json(name = "posterHeight")
    val posterHeight: kotlin.Int,

    @Json(name = "duration")
    val duration: kotlin.Int,

    @Json(name = "ui_id")
    val uiId: kotlin.String? = null,

    @Json(name = "latitude")
    val latitude: kotlin.Double? = null,

    @Json(name = "longitude")
    val longitude: kotlin.Double? = null,

    @Json(name = "at")
    val at: java.time.OffsetDateTime? = null,

    @Json(name = "locationID")
    val locationID: kotlin.Int? = null

)

