/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.r3chain.data.api.models

import io.r3chain.data.api.models.PlasticWeightDto

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param wasteRecordID 
 * @param weightDto 
 */


data class TraceWasteRecordDto (

    @Json(name = "wasteRecordID")
    val wasteRecordID: kotlin.Int? = null,

    @Json(name = "weightDto")
    val weightDto: PlasticWeightDto? = null

)

