/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.r3chain.data.api.models

import io.r3chain.data.api.models.EnumWasteRecordDispatchMode
import io.r3chain.data.api.models.WasteRecordDto

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param wasteRecord 
 * @param parentWasteRecordIDList 
 * @param dispatchMode 
 */


data class WasteRecordSaveRequestDto (

    @Json(name = "wasteRecord")
    val wasteRecord: WasteRecordDto,

    @Json(name = "parentWasteRecordIDList")
    val parentWasteRecordIDList: kotlin.collections.List<kotlin.Int>,

    @Json(name = "dispatchMode")
    val dispatchMode: EnumWasteRecordDispatchMode

)

