/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.r3chain.data.api.models

import io.r3chain.data.api.models.EnumWasteRecordLinkMode
import io.r3chain.data.api.models.EnumWasteRecordStage
import io.r3chain.data.api.models.EnumWasteRecordState
import io.r3chain.data.api.models.EnumWasteRecordStatus
import io.r3chain.data.api.models.EnumWasteRecordType
import io.r3chain.data.api.models.KeyValuePairDto
import io.r3chain.data.api.models.PlasticWeightDto
import io.r3chain.data.api.models.WasteRecordVerificationDto

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param state 
 * @param status 
 * @param stage 
 * @param type 
 * @param linkMode 
 * @param isActiveRecord 
 * @param partnerIDList 
 * @param wasteRecordTransitionFromIDList 
 * @param wasteRecordTransitionToIDList 
 * @param wasteRecordVerificationList 
 * @param customTags 
 * @param plasticWeight 
 * @param uiId 
 * @param resourceIDList 
 * @param locationID 
 * @param at 
 * @param processingMethod 
 * @param processingMaterialForm 
 * @param processingColor 
 */


data class WasteRecordDto (

    @Json(name = "id")
    val id: kotlin.Int,

    @Json(name = "state")
    val state: EnumWasteRecordState,

    @Json(name = "status")
    val status: EnumWasteRecordStatus,

    @Json(name = "stage")
    val stage: EnumWasteRecordStage,

    @Json(name = "type")
    val type: EnumWasteRecordType,

    @Json(name = "linkMode")
    val linkMode: EnumWasteRecordLinkMode,

    @Json(name = "isActiveRecord")
    val isActiveRecord: kotlin.Boolean,

    @Json(name = "partnerIDList")
    val partnerIDList: kotlin.collections.List<kotlin.Int>,

    @Json(name = "wasteRecordTransitionFromIDList")
    val wasteRecordTransitionFromIDList: kotlin.collections.List<kotlin.Int>,

    @Json(name = "wasteRecordTransitionToIDList")
    val wasteRecordTransitionToIDList: kotlin.collections.List<kotlin.Int>,

    @Json(name = "wasteRecordVerificationList")
    val wasteRecordVerificationList: kotlin.collections.List<WasteRecordVerificationDto>,

    @Json(name = "customTags")
    val customTags: kotlin.collections.List<KeyValuePairDto>,

    @Json(name = "plasticWeight")
    val plasticWeight: PlasticWeightDto,

    @Json(name = "ui_id")
    val uiId: kotlin.String? = null,

    @Json(name = "resourceIDList")
    val resourceIDList: kotlin.collections.List<kotlin.Int>? = null,

    @Json(name = "locationID")
    val locationID: kotlin.Int? = null,

    @Json(name = "at")
    val at: java.time.OffsetDateTime? = null,

    @Json(name = "processingMethod")
    val processingMethod: kotlin.String? = null,

    @Json(name = "processingMaterialForm")
    val processingMaterialForm: kotlin.String? = null,

    @Json(name = "processingColor")
    val processingColor: kotlin.String? = null

)

