/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.r3chain.data.api.models

import io.r3chain.data.api.models.EnumWasteVerificationType
import io.r3chain.data.api.models.PlasticWeightDto

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param verificationType 
 * @param plasticWeight 
 * @param commonResourceIDList 
 * @param weightSlipResourceIDList 
 * @param vehicleNumber 
 * @param description 
 * @param locationID 
 * @param at 
 */


data class WasteRecordVerificationDto (

    @Json(name = "id")
    val id: kotlin.Int,

    @Json(name = "verificationType")
    val verificationType: EnumWasteVerificationType,

    @Json(name = "plasticWeight")
    val plasticWeight: PlasticWeightDto,

    @Json(name = "commonResourceIDList")
    val commonResourceIDList: kotlin.collections.List<kotlin.Int>? = null,

    @Json(name = "weightSlipResourceIDList")
    val weightSlipResourceIDList: kotlin.collections.List<kotlin.Int>? = null,

    @Json(name = "vehicleNumber")
    val vehicleNumber: kotlin.String? = null,

    @Json(name = "description")
    val description: kotlin.String? = null,

    @Json(name = "locationID")
    val locationID: kotlin.Int? = null,

    @Json(name = "at")
    val at: java.time.OffsetDateTime? = null

)

