/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.r3chain.data.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.r3chain.data.api.models.AuthResponseEntity
import io.r3chain.data.api.models.ApiStatusCode
import io.r3chain.data.api.models.AuthDto
import io.r3chain.data.api.models.ErrorEntity
import io.r3chain.data.api.models.OrganizationDto
import io.r3chain.data.api.models.OrganizationUserDto
import io.r3chain.data.api.models.ResourceDto
import io.r3chain.data.api.models.SessionDto

class AuthResponseEntityTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AuthResponseEntity
        //val modelInstance = AuthResponseEntity()

        // to test the property `statusCode`
        should("test statusCode") {
            // uncomment below to test the property
            //modelInstance.statusCode shouldBe ("TODO")
        }

        // to test the property `message`
        should("test message") {
            // uncomment below to test the property
            //modelInstance.message shouldBe ("TODO")
        }

        // to test the property `errorList`
        should("test errorList") {
            // uncomment below to test the property
            //modelInstance.errorList shouldBe ("TODO")
        }

        // to test the property `responseResourceList`
        should("test responseResourceList") {
            // uncomment below to test the property
            //modelInstance.responseResourceList shouldBe ("TODO")
        }

        // to test the property `sessionList`
        should("test sessionList") {
            // uncomment below to test the property
            //modelInstance.sessionList shouldBe ("TODO")
        }

        // to test the property `organizationList`
        should("test organizationList") {
            // uncomment below to test the property
            //modelInstance.organizationList shouldBe ("TODO")
        }

        // to test the property `organizationUserList`
        should("test organizationUserList") {
            // uncomment below to test the property
            //modelInstance.organizationUserList shouldBe ("TODO")
        }

        // to test the property `authList`
        should("test authList") {
            // uncomment below to test the property
            //modelInstance.authList shouldBe ("TODO")
        }

    }
}
