/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.r3chain.data.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.r3chain.data.api.models.AuthSaveRequestDto
import io.r3chain.data.api.models.AuthDto

class AuthSaveRequestDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AuthSaveRequestDto
        //val modelInstance = AuthSaveRequestDto()

        // to test the property `auth`
        should("test auth") {
            // uncomment below to test the property
            //modelInstance.auth shouldBe ("TODO")
        }

    }
}
