/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.r3chain.data.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.r3chain.data.api.models.FacilityDto
import io.r3chain.data.api.models.EnumCapacityUnit
import io.r3chain.data.api.models.EnumCollectionType
import io.r3chain.data.api.models.EnumFacilityProcessingMethod
import io.r3chain.data.api.models.EnumFacilityProcessingType
import io.r3chain.data.api.models.EnumFacilityState
import io.r3chain.data.api.models.EnumFacilityType
import io.r3chain.data.api.models.EnumPlasticType
import io.r3chain.data.api.models.KeyValuePairDto

class FacilityDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of FacilityDto
        //val modelInstance = FacilityDto()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `state`
        should("test state") {
            // uncomment below to test the property
            //modelInstance.state shouldBe ("TODO")
        }

        // to test the property `locationID`
        should("test locationID") {
            // uncomment below to test the property
            //modelInstance.locationID shouldBe ("TODO")
        }

        // to test the property `customTags`
        should("test customTags") {
            // uncomment below to test the property
            //modelInstance.customTags shouldBe ("TODO")
        }

        // to test the property `resourceIDList`
        should("test resourceIDList") {
            // uncomment below to test the property
            //modelInstance.resourceIDList shouldBe ("TODO")
        }

        // to test the property `inboundWasteTypeList`
        should("test inboundWasteTypeList") {
            // uncomment below to test the property
            //modelInstance.inboundWasteTypeList shouldBe ("TODO")
        }

        // to test the property `outboundWasteTypeList`
        should("test outboundWasteTypeList") {
            // uncomment below to test the property
            //modelInstance.outboundWasteTypeList shouldBe ("TODO")
        }

        // to test the property `capacity`
        should("test capacity") {
            // uncomment below to test the property
            //modelInstance.capacity shouldBe ("TODO")
        }

        // to test the property `capacityUnit`
        should("test capacityUnit") {
            // uncomment below to test the property
            //modelInstance.capacityUnit shouldBe ("TODO")
        }

        // to test the property `uiId`
        should("test uiId") {
            // uncomment below to test the property
            //modelInstance.uiId shouldBe ("TODO")
        }

        // to test the property `certificateValidityAt`
        should("test certificateValidityAt") {
            // uncomment below to test the property
            //modelInstance.certificateValidityAt shouldBe ("TODO")
        }

        // to test the property `certificateResourceID`
        should("test certificateResourceID") {
            // uncomment below to test the property
            //modelInstance.certificateResourceID shouldBe ("TODO")
        }

        // to test the property `collectionType`
        should("test collectionType") {
            // uncomment below to test the property
            //modelInstance.collectionType shouldBe ("TODO")
        }

        // to test the property `collectionSource`
        should("test collectionSource") {
            // uncomment below to test the property
            //modelInstance.collectionSource shouldBe ("TODO")
        }

        // to test the property `processingType`
        should("test processingType") {
            // uncomment below to test the property
            //modelInstance.processingType shouldBe ("TODO")
        }

        // to test the property `processingMethod`
        should("test processingMethod") {
            // uncomment below to test the property
            //modelInstance.processingMethod shouldBe ("TODO")
        }

        // to test the property `processingForm`
        should("test processingForm") {
            // uncomment below to test the property
            //modelInstance.processingForm shouldBe ("TODO")
        }

        // to test the property `deliveryToFacilityID`
        should("test deliveryToFacilityID") {
            // uncomment below to test the property
            //modelInstance.deliveryToFacilityID shouldBe ("TODO")
        }

        // to test the property `deliveryToPartnerID`
        should("test deliveryToPartnerID") {
            // uncomment below to test the property
            //modelInstance.deliveryToPartnerID shouldBe ("TODO")
        }

    }
}
