/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.r3chain.data.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.r3chain.data.api.models.FacilitySaveRequestDto
import io.r3chain.data.api.models.FacilityDto

class FacilitySaveRequestDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of FacilitySaveRequestDto
        //val modelInstance = FacilitySaveRequestDto()

        // to test the property `facility`
        should("test facility") {
            // uncomment below to test the property
            //modelInstance.facility shouldBe ("TODO")
        }

    }
}
