/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.r3chain.data.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.r3chain.data.api.models.FacilityListRequestDto
import io.r3chain.data.api.models.EnumFacilityType

class FacilityListRequestDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of FacilityListRequestDto
        //val modelInstance = FacilityListRequestDto()

        // to test the property `facilityIDList`
        should("test facilityIDList") {
            // uncomment below to test the property
            //modelInstance.facilityIDList shouldBe ("TODO")
        }

        // to test the property `facilityTypeList`
        should("test facilityTypeList") {
            // uncomment below to test the property
            //modelInstance.facilityTypeList shouldBe ("TODO")
        }

    }
}
