/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.r3chain.data.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.r3chain.data.api.models.LocationSaveDto

class LocationSaveDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of LocationSaveDto
        //val modelInstance = LocationSaveDto()

        // to test the property `googlePlaceID`
        should("test googlePlaceID") {
            // uncomment below to test the property
            //modelInstance.googlePlaceID shouldBe ("TODO")
        }

        // to test the property `rawAddress`
        should("test rawAddress") {
            // uncomment below to test the property
            //modelInstance.rawAddress shouldBe ("TODO")
        }

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `uiId`
        should("test uiId") {
            // uncomment below to test the property
            //modelInstance.uiId shouldBe ("TODO")
        }

    }
}
