/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.r3chain.data.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.r3chain.data.api.models.LocationSaveRequestDto
import io.r3chain.data.api.models.LocationSaveDto

class LocationSaveRequestDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of LocationSaveRequestDto
        //val modelInstance = LocationSaveRequestDto()

        // to test the property `location`
        should("test location") {
            // uncomment below to test the property
            //modelInstance.location shouldBe ("TODO")
        }

    }
}
