/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.r3chain.data.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.r3chain.data.api.models.OrganizationUserSaveRequestDto
import io.r3chain.data.api.models.OrganizationUserDto

class OrganizationUserSaveRequestDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of OrganizationUserSaveRequestDto
        //val modelInstance = OrganizationUserSaveRequestDto()

        // to test the property `organizationUser`
        should("test organizationUser") {
            // uncomment below to test the property
            //modelInstance.organizationUser shouldBe ("TODO")
        }

    }
}
