/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.r3chain.data.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.r3chain.data.api.models.OrganizationUserResponseEntity
import io.r3chain.data.api.models.ApiStatusCode
import io.r3chain.data.api.models.ErrorEntity
import io.r3chain.data.api.models.OrganizationDto
import io.r3chain.data.api.models.OrganizationUserDto
import io.r3chain.data.api.models.ResourceDto

class OrganizationUserResponseEntityTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of OrganizationUserResponseEntity
        //val modelInstance = OrganizationUserResponseEntity()

        // to test the property `statusCode`
        should("test statusCode") {
            // uncomment below to test the property
            //modelInstance.statusCode shouldBe ("TODO")
        }

        // to test the property `message`
        should("test message") {
            // uncomment below to test the property
            //modelInstance.message shouldBe ("TODO")
        }

        // to test the property `errorList`
        should("test errorList") {
            // uncomment below to test the property
            //modelInstance.errorList shouldBe ("TODO")
        }

        // to test the property `responseResourceList`
        should("test responseResourceList") {
            // uncomment below to test the property
            //modelInstance.responseResourceList shouldBe ("TODO")
        }

        // to test the property `organizationList`
        should("test organizationList") {
            // uncomment below to test the property
            //modelInstance.organizationList shouldBe ("TODO")
        }

        // to test the property `organizationUserList`
        should("test organizationUserList") {
            // uncomment below to test the property
            //modelInstance.organizationUserList shouldBe ("TODO")
        }

    }
}
