/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.r3chain.data.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.r3chain.data.api.models.OrganizationSaveRequestDto
import io.r3chain.data.api.models.OrganizationDto

class OrganizationSaveRequestDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of OrganizationSaveRequestDto
        //val modelInstance = OrganizationSaveRequestDto()

        // to test the property `organization`
        should("test organization") {
            // uncomment below to test the property
            //modelInstance.organization shouldBe ("TODO")
        }

    }
}
