/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.r3chain.data.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.r3chain.data.api.models.PartnerDto
import io.r3chain.data.api.models.EnumPartnerInboundSource
import io.r3chain.data.api.models.EnumPartnerInboundType
import io.r3chain.data.api.models.EnumPartnerOutboundMethod
import io.r3chain.data.api.models.EnumPartnerOutboundType
import io.r3chain.data.api.models.EnumPartnerState
import io.r3chain.data.api.models.EnumPartnerType
import io.r3chain.data.api.models.EnumPlasticType
import io.r3chain.data.api.models.KeyValuePairDto

class PartnerDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PartnerDto
        //val modelInstance = PartnerDto()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `state`
        should("test state") {
            // uncomment below to test the property
            //modelInstance.state shouldBe ("TODO")
        }

        // to test the property `locationID`
        should("test locationID") {
            // uncomment below to test the property
            //modelInstance.locationID shouldBe ("TODO")
        }

        // to test the property `contact`
        should("test contact") {
            // uncomment below to test the property
            //modelInstance.contact shouldBe ("TODO")
        }

        // to test the property `customTags`
        should("test customTags") {
            // uncomment below to test the property
            //modelInstance.customTags shouldBe ("TODO")
        }

        // to test the property `resourceIDList`
        should("test resourceIDList") {
            // uncomment below to test the property
            //modelInstance.resourceIDList shouldBe ("TODO")
        }

        // to test the property `uiId`
        should("test uiId") {
            // uncomment below to test the property
            //modelInstance.uiId shouldBe ("TODO")
        }

        // to test the property `organizationOwnerID`
        should("test organizationOwnerID") {
            // uncomment below to test the property
            //modelInstance.organizationOwnerID shouldBe ("TODO")
        }

        // to test the property `inboundType`
        should("test inboundType") {
            // uncomment below to test the property
            //modelInstance.inboundType shouldBe ("TODO")
        }

        // to test the property `inboundSource`
        should("test inboundSource") {
            // uncomment below to test the property
            //modelInstance.inboundSource shouldBe ("TODO")
        }

        // to test the property `inboundWasteTypeList`
        should("test inboundWasteTypeList") {
            // uncomment below to test the property
            //modelInstance.inboundWasteTypeList shouldBe ("TODO")
        }

        // to test the property `inboundIsSorting`
        should("test inboundIsSorting") {
            // uncomment below to test the property
            //modelInstance.inboundIsSorting shouldBe ("TODO")
        }

        // to test the property `outboundType`
        should("test outboundType") {
            // uncomment below to test the property
            //modelInstance.outboundType shouldBe ("TODO")
        }

        // to test the property `outboundMethod`
        should("test outboundMethod") {
            // uncomment below to test the property
            //modelInstance.outboundMethod shouldBe ("TODO")
        }

        // to test the property `outboundMaterialList`
        should("test outboundMaterialList") {
            // uncomment below to test the property
            //modelInstance.outboundMaterialList shouldBe ("TODO")
        }

    }
}
