/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.r3chain.data.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.r3chain.data.api.models.PartnerSaveRequestDto
import io.r3chain.data.api.models.PartnerDto

class PartnerSaveRequestDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PartnerSaveRequestDto
        //val modelInstance = PartnerSaveRequestDto()

        // to test the property `partner`
        should("test partner") {
            // uncomment below to test the property
            //modelInstance.partner shouldBe ("TODO")
        }

    }
}
