/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.r3chain.data.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.r3chain.data.api.models.PlasticWeightDto
import io.r3chain.data.api.models.EnumPlasticType

class PlasticWeightDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PlasticWeightDto
        //val modelInstance = PlasticWeightDto()

        // to test the property `plasticTypeList`
        should("test plasticTypeList") {
            // uncomment below to test the property
            //modelInstance.plasticTypeList shouldBe ("TODO")
        }

        // to test the property `netWeight`
        should("test netWeight") {
            // uncomment below to test the property
            //modelInstance.netWeight shouldBe ("TODO")
        }

        // to test the property `grossWeight`
        should("test grossWeight") {
            // uncomment below to test the property
            //modelInstance.grossWeight shouldBe ("TODO")
        }

        // to test the property `tareWeight`
        should("test tareWeight") {
            // uncomment below to test the property
            //modelInstance.tareWeight shouldBe ("TODO")
        }

    }
}
