/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.r3chain.data.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.r3chain.data.api.models.ResourceDto
import io.r3chain.data.api.models.EnumFileType

class ResourceDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ResourceDto
        //val modelInstance = ResourceDto()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `filePath`
        should("test filePath") {
            // uncomment below to test the property
            //modelInstance.filePath shouldBe ("TODO")
        }

        // to test the property `fileType`
        should("test fileType") {
            // uncomment below to test the property
            //modelInstance.fileType shouldBe ("TODO")
        }

        // to test the property `fileSize`
        should("test fileSize") {
            // uncomment below to test the property
            //modelInstance.fileSize shouldBe ("TODO")
        }

        // to test the property `mimeType`
        should("test mimeType") {
            // uncomment below to test the property
            //modelInstance.mimeType shouldBe ("TODO")
        }

        // to test the property `width`
        should("test width") {
            // uncomment below to test the property
            //modelInstance.width shouldBe ("TODO")
        }

        // to test the property `height`
        should("test height") {
            // uncomment below to test the property
            //modelInstance.height shouldBe ("TODO")
        }

        // to test the property `posterFilePath`
        should("test posterFilePath") {
            // uncomment below to test the property
            //modelInstance.posterFilePath shouldBe ("TODO")
        }

        // to test the property `posterWidth`
        should("test posterWidth") {
            // uncomment below to test the property
            //modelInstance.posterWidth shouldBe ("TODO")
        }

        // to test the property `posterHeight`
        should("test posterHeight") {
            // uncomment below to test the property
            //modelInstance.posterHeight shouldBe ("TODO")
        }

        // to test the property `duration`
        should("test duration") {
            // uncomment below to test the property
            //modelInstance.duration shouldBe ("TODO")
        }

        // to test the property `uiId`
        should("test uiId") {
            // uncomment below to test the property
            //modelInstance.uiId shouldBe ("TODO")
        }

        // to test the property `latitude`
        should("test latitude") {
            // uncomment below to test the property
            //modelInstance.latitude shouldBe ("TODO")
        }

        // to test the property `longitude`
        should("test longitude") {
            // uncomment below to test the property
            //modelInstance.longitude shouldBe ("TODO")
        }

        // to test the property `at`
        should("test at") {
            // uncomment below to test the property
            //modelInstance.at shouldBe ("TODO")
        }

        // to test the property `locationID`
        should("test locationID") {
            // uncomment below to test the property
            //modelInstance.locationID shouldBe ("TODO")
        }

    }
}
