/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.r3chain.data.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.r3chain.data.api.models.ResourceUploadDto

class ResourceUploadDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ResourceUploadDto
        //val modelInstance = ResourceUploadDto()

        // to test the property `uiId`
        should("test uiId") {
            // uncomment below to test the property
            //modelInstance.uiId shouldBe ("TODO")
        }

    }
}
