/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.r3chain.data.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.r3chain.data.api.models.ResourceUploadRequestDto
import io.r3chain.data.api.models.ResourceUploadDto

class ResourceUploadRequestDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ResourceUploadRequestDto
        //val modelInstance = ResourceUploadRequestDto()

        // to test the property `resourceList`
        should("test resourceList") {
            // uncomment below to test the property
            //modelInstance.resourceList shouldBe ("TODO")
        }

    }
}
