/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.r3chain.data.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.r3chain.data.api.models.SessionDto

class SessionDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SessionDto
        //val modelInstance = SessionDto()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `token`
        should("test token") {
            // uncomment below to test the property
            //modelInstance.token shouldBe ("TODO")
        }

        // to test the property `authID`
        should("test authID") {
            // uncomment below to test the property
            //modelInstance.authID shouldBe ("TODO")
        }

        // to test the property `uiId`
        should("test uiId") {
            // uncomment below to test the property
            //modelInstance.uiId shouldBe ("TODO")
        }

    }
}
