/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.r3chain.data.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.r3chain.data.api.models.TraceStepDto
import io.r3chain.data.api.models.EnumPartnerType
import io.r3chain.data.api.models.PlasticWeightDto
import io.r3chain.data.api.models.TraceWasteTypeRecordDto

class TraceStepDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TraceStepDto
        //val modelInstance = TraceStepDto()

        // to test the property `stepType`
        should("test stepType") {
            // uncomment below to test the property
            //modelInstance.stepType shouldBe ("TODO")
        }

        // to test the property `traceTypeWasteRecordListDto`
        should("test traceTypeWasteRecordListDto") {
            // uncomment below to test the property
            //modelInstance.traceTypeWasteRecordListDto shouldBe ("TODO")
        }

        // to test the property `weightDto`
        should("test weightDto") {
            // uncomment below to test the property
            //modelInstance.weightDto shouldBe ("TODO")
        }

    }
}
