/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.r3chain.data.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.r3chain.data.api.models.TraceWasteTypeRecordDto
import io.r3chain.data.api.models.EnumPlasticType
import io.r3chain.data.api.models.PlasticWeightDto
import io.r3chain.data.api.models.TraceWasteRecordDto

class TraceWasteTypeRecordDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TraceWasteTypeRecordDto
        //val modelInstance = TraceWasteTypeRecordDto()

        // to test the property `tracePlasticType`
        should("test tracePlasticType") {
            // uncomment below to test the property
            //modelInstance.tracePlasticType shouldBe ("TODO")
        }

        // to test the property `traceWasteRecordListDto`
        should("test traceWasteRecordListDto") {
            // uncomment below to test the property
            //modelInstance.traceWasteRecordListDto shouldBe ("TODO")
        }

        // to test the property `weightDto`
        should("test weightDto") {
            // uncomment below to test the property
            //modelInstance.weightDto shouldBe ("TODO")
        }

    }
}
