/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.r3chain.data.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.r3chain.data.api.models.TraceWasteRecordDto
import io.r3chain.data.api.models.PlasticWeightDto

class TraceWasteRecordDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TraceWasteRecordDto
        //val modelInstance = TraceWasteRecordDto()

        // to test the property `wasteRecordID`
        should("test wasteRecordID") {
            // uncomment below to test the property
            //modelInstance.wasteRecordID shouldBe ("TODO")
        }

        // to test the property `weightDto`
        should("test weightDto") {
            // uncomment below to test the property
            //modelInstance.weightDto shouldBe ("TODO")
        }

    }
}
