/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.r3chain.data.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.r3chain.data.api.models.TraceListRequestDto

class TraceListRequestDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TraceListRequestDto
        //val modelInstance = TraceListRequestDto()

        // to test the property `wasteRecordIDList`
        should("test wasteRecordIDList") {
            // uncomment below to test the property
            //modelInstance.wasteRecordIDList shouldBe ("TODO")
        }

    }
}
