/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.r3chain.data.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.r3chain.data.api.models.WasteRecordSaveRequestDto
import io.r3chain.data.api.models.EnumWasteRecordDispatchMode
import io.r3chain.data.api.models.WasteRecordDto

class WasteRecordSaveRequestDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of WasteRecordSaveRequestDto
        //val modelInstance = WasteRecordSaveRequestDto()

        // to test the property `wasteRecord`
        should("test wasteRecord") {
            // uncomment below to test the property
            //modelInstance.wasteRecord shouldBe ("TODO")
        }

        // to test the property `parentWasteRecordIDList`
        should("test parentWasteRecordIDList") {
            // uncomment below to test the property
            //modelInstance.parentWasteRecordIDList shouldBe ("TODO")
        }

        // to test the property `dispatchMode`
        should("test dispatchMode") {
            // uncomment below to test the property
            //modelInstance.dispatchMode shouldBe ("TODO")
        }

    }
}
