/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.r3chain.data.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.r3chain.data.api.models.WasteRecordDto
import io.r3chain.data.api.models.EnumWasteRecordLinkMode
import io.r3chain.data.api.models.EnumWasteRecordStage
import io.r3chain.data.api.models.EnumWasteRecordState
import io.r3chain.data.api.models.EnumWasteRecordStatus
import io.r3chain.data.api.models.EnumWasteRecordType
import io.r3chain.data.api.models.KeyValuePairDto
import io.r3chain.data.api.models.PlasticWeightDto
import io.r3chain.data.api.models.WasteRecordVerificationDto

class WasteRecordDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of WasteRecordDto
        //val modelInstance = WasteRecordDto()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `state`
        should("test state") {
            // uncomment below to test the property
            //modelInstance.state shouldBe ("TODO")
        }

        // to test the property `status`
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `stage`
        should("test stage") {
            // uncomment below to test the property
            //modelInstance.stage shouldBe ("TODO")
        }

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `linkMode`
        should("test linkMode") {
            // uncomment below to test the property
            //modelInstance.linkMode shouldBe ("TODO")
        }

        // to test the property `isActiveRecord`
        should("test isActiveRecord") {
            // uncomment below to test the property
            //modelInstance.isActiveRecord shouldBe ("TODO")
        }

        // to test the property `partnerIDList`
        should("test partnerIDList") {
            // uncomment below to test the property
            //modelInstance.partnerIDList shouldBe ("TODO")
        }

        // to test the property `wasteRecordTransitionFromIDList`
        should("test wasteRecordTransitionFromIDList") {
            // uncomment below to test the property
            //modelInstance.wasteRecordTransitionFromIDList shouldBe ("TODO")
        }

        // to test the property `wasteRecordTransitionToIDList`
        should("test wasteRecordTransitionToIDList") {
            // uncomment below to test the property
            //modelInstance.wasteRecordTransitionToIDList shouldBe ("TODO")
        }

        // to test the property `wasteRecordVerificationList`
        should("test wasteRecordVerificationList") {
            // uncomment below to test the property
            //modelInstance.wasteRecordVerificationList shouldBe ("TODO")
        }

        // to test the property `customTags`
        should("test customTags") {
            // uncomment below to test the property
            //modelInstance.customTags shouldBe ("TODO")
        }

        // to test the property `plasticWeight`
        should("test plasticWeight") {
            // uncomment below to test the property
            //modelInstance.plasticWeight shouldBe ("TODO")
        }

        // to test the property `uiId`
        should("test uiId") {
            // uncomment below to test the property
            //modelInstance.uiId shouldBe ("TODO")
        }

        // to test the property `resourceIDList`
        should("test resourceIDList") {
            // uncomment below to test the property
            //modelInstance.resourceIDList shouldBe ("TODO")
        }

        // to test the property `locationID`
        should("test locationID") {
            // uncomment below to test the property
            //modelInstance.locationID shouldBe ("TODO")
        }

        // to test the property `at`
        should("test at") {
            // uncomment below to test the property
            //modelInstance.at shouldBe ("TODO")
        }

        // to test the property `processingMethod`
        should("test processingMethod") {
            // uncomment below to test the property
            //modelInstance.processingMethod shouldBe ("TODO")
        }

        // to test the property `processingMaterialForm`
        should("test processingMaterialForm") {
            // uncomment below to test the property
            //modelInstance.processingMaterialForm shouldBe ("TODO")
        }

        // to test the property `processingColor`
        should("test processingColor") {
            // uncomment below to test the property
            //modelInstance.processingColor shouldBe ("TODO")
        }

    }
}
