/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.r3chain.data.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.r3chain.data.api.models.WasteRecordListRequestDto
import io.r3chain.data.api.models.EnumPartnerType

class WasteRecordListRequestDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of WasteRecordListRequestDto
        //val modelInstance = WasteRecordListRequestDto()

        // to test the property `partnerTypeList`
        should("test partnerTypeList") {
            // uncomment below to test the property
            //modelInstance.partnerTypeList shouldBe ("TODO")
        }

        // to test the property `partnerIDList`
        should("test partnerIDList") {
            // uncomment below to test the property
            //modelInstance.partnerIDList shouldBe ("TODO")
        }

        // to test the property `wasteRecordIDList`
        should("test wasteRecordIDList") {
            // uncomment below to test the property
            //modelInstance.wasteRecordIDList shouldBe ("TODO")
        }

    }
}
