/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.r3chain.data.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.r3chain.data.api.models.WasteRecordVerificationDto
import io.r3chain.data.api.models.EnumWasteVerificationType
import io.r3chain.data.api.models.PlasticWeightDto

class WasteRecordVerificationDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of WasteRecordVerificationDto
        //val modelInstance = WasteRecordVerificationDto()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `verificationType`
        should("test verificationType") {
            // uncomment below to test the property
            //modelInstance.verificationType shouldBe ("TODO")
        }

        // to test the property `plasticWeight`
        should("test plasticWeight") {
            // uncomment below to test the property
            //modelInstance.plasticWeight shouldBe ("TODO")
        }

        // to test the property `commonResourceIDList`
        should("test commonResourceIDList") {
            // uncomment below to test the property
            //modelInstance.commonResourceIDList shouldBe ("TODO")
        }

        // to test the property `weightSlipResourceIDList`
        should("test weightSlipResourceIDList") {
            // uncomment below to test the property
            //modelInstance.weightSlipResourceIDList shouldBe ("TODO")
        }

        // to test the property `vehicleNumber`
        should("test vehicleNumber") {
            // uncomment below to test the property
            //modelInstance.vehicleNumber shouldBe ("TODO")
        }

        // to test the property `description`
        should("test description") {
            // uncomment below to test the property
            //modelInstance.description shouldBe ("TODO")
        }

        // to test the property `locationID`
        should("test locationID") {
            // uncomment below to test the property
            //modelInstance.locationID shouldBe ("TODO")
        }

        // to test the property `at`
        should("test at") {
            // uncomment below to test the property
            //modelInstance.at shouldBe ("TODO")
        }

    }
}
