/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.r3chain.data.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.r3chain.data.api.models.WasteRecordResponseEntity
import io.r3chain.data.api.models.ApiStatusCode
import io.r3chain.data.api.models.ErrorEntity
import io.r3chain.data.api.models.LocationDto
import io.r3chain.data.api.models.ResourceDto
import io.r3chain.data.api.models.WasteRecordDto
import io.r3chain.data.api.models.WasteRecordTransitionDto

class WasteRecordResponseEntityTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of WasteRecordResponseEntity
        //val modelInstance = WasteRecordResponseEntity()

        // to test the property `statusCode`
        should("test statusCode") {
            // uncomment below to test the property
            //modelInstance.statusCode shouldBe ("TODO")
        }

        // to test the property `message`
        should("test message") {
            // uncomment below to test the property
            //modelInstance.message shouldBe ("TODO")
        }

        // to test the property `errorList`
        should("test errorList") {
            // uncomment below to test the property
            //modelInstance.errorList shouldBe ("TODO")
        }

        // to test the property `responseResourceList`
        should("test responseResourceList") {
            // uncomment below to test the property
            //modelInstance.responseResourceList shouldBe ("TODO")
        }

        // to test the property `wasteRecordList`
        should("test wasteRecordList") {
            // uncomment below to test the property
            //modelInstance.wasteRecordList shouldBe ("TODO")
        }

        // to test the property `wasteRecordTransitionList`
        should("test wasteRecordTransitionList") {
            // uncomment below to test the property
            //modelInstance.wasteRecordTransitionList shouldBe ("TODO")
        }

        // to test the property `locationList`
        should("test locationList") {
            // uncomment below to test the property
            //modelInstance.locationList shouldBe ("TODO")
        }

    }
}
