/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.r3chain.data.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.r3chain.data.api.models.WasteRecordTransitionDto
import io.r3chain.data.api.models.EnumWasteRecordTransitionType

class WasteRecordTransitionDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of WasteRecordTransitionDto
        //val modelInstance = WasteRecordTransitionDto()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `wasteRecordTransitionFromID`
        should("test wasteRecordTransitionFromID") {
            // uncomment below to test the property
            //modelInstance.wasteRecordTransitionFromID shouldBe ("TODO")
        }

        // to test the property `wasteRecordTransitionTransitionToID`
        should("test wasteRecordTransitionTransitionToID") {
            // uncomment below to test the property
            //modelInstance.wasteRecordTransitionTransitionToID shouldBe ("TODO")
        }

        // to test the property `uiId`
        should("test uiId") {
            // uncomment below to test the property
            //modelInstance.uiId shouldBe ("TODO")
        }

        // to test the property `resourceIDList`
        should("test resourceIDList") {
            // uncomment below to test the property
            //modelInstance.resourceIDList shouldBe ("TODO")
        }

    }
}
