/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.r3chain.core.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * Values: HOUSEHOLD,CLEANUP,DEPOSIT_REFUND_SYSTEM,OTHER
 */

@JsonClass(generateAdapter = false)
enum class EnumPartnerInboundSource(val value: kotlin.String) {

    @Json(name = "household")
    HOUSEHOLD("household"),

    @Json(name = "cleanup")
    CLEANUP("cleanup"),

    @Json(name = "depositRefundSystem")
    DEPOSIT_REFUND_SYSTEM("depositRefundSystem"),

    @Json(name = "other")
    OTHER("other");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is EnumPartnerInboundSource) "$data" else null

        /**
         * Returns a valid [EnumPartnerInboundSource] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): EnumPartnerInboundSource? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

