/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.r3chain.core.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * Values: PET,HDPE,PVC,LDPE,PP,PS,OTHER
 */

@JsonClass(generateAdapter = false)
enum class EnumPlasticType(val value: kotlin.String) {

    @Json(name = "pet")
    PET("pet"),

    @Json(name = "hdpe")
    HDPE("hdpe"),

    @Json(name = "pvc")
    PVC("pvc"),

    @Json(name = "ldpe")
    LDPE("ldpe"),

    @Json(name = "pp")
    PP("pp"),

    @Json(name = "ps")
    PS("ps"),

    @Json(name = "other")
    OTHER("other");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is EnumPlasticType) "$data" else null

        /**
         * Returns a valid [EnumPlasticType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): EnumPlasticType? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

