/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.r3chain.core.api.models

import io.r3chain.core.api.models.EnumFacilityType

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param facilityIDList 
 * @param facilityTypeList 
 */


data class FacilityListRequestDto (

    @Json(name = "facilityIDList")
    val facilityIDList: kotlin.collections.List<kotlin.Int>,

    @Json(name = "facilityTypeList")
    val facilityTypeList: kotlin.collections.List<EnumFacilityType>

)

