/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.r3chain.core.api.models

import io.r3chain.core.api.models.ApiStatusCode
import io.r3chain.core.api.models.ErrorEntity
import io.r3chain.core.api.models.FacilityDto
import io.r3chain.core.api.models.LocationDto
import io.r3chain.core.api.models.OrganizationDto
import io.r3chain.core.api.models.ResourceDto

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param statusCode 
 * @param message 
 * @param errorList 
 * @param responseResourceList 
 * @param facilityList 
 * @param organizationList 
 * @param locationList 
 */


data class FacilityResponseEntity (

    @Json(name = "statusCode")
    val statusCode: ApiStatusCode? = null,

    @Json(name = "message")
    val message: kotlin.String? = null,

    @Json(name = "errorList")
    val errorList: kotlin.collections.List<ErrorEntity>? = null,

    @Json(name = "responseResourceList")
    val responseResourceList: kotlin.collections.Map<kotlin.String, ResourceDto>? = null,

    @Json(name = "facilityList")
    val facilityList: kotlin.collections.Map<kotlin.String, FacilityDto>? = null,

    @Json(name = "organizationList")
    val organizationList: kotlin.collections.Map<kotlin.String, OrganizationDto>? = null,

    @Json(name = "locationList")
    val locationList: kotlin.collections.Map<kotlin.String, LocationDto>? = null

)

