/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.r3chain.core.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param googlePlaceID 
 * @param rawAddress 
 * @param id 
 * @param country 
 * @param region 
 * @param city 
 * @param address 
 * @param latitude 
 * @param longitude 
 * @param postalCode 
 * @param radius 
 * @param uiId 
 */


data class LocationDto (

    @Json(name = "googlePlaceID")
    val googlePlaceID: kotlin.String,

    @Json(name = "rawAddress")
    val rawAddress: kotlin.String,

    @Json(name = "id")
    val id: kotlin.Int,

    @Json(name = "country")
    val country: kotlin.String,

    @Json(name = "region")
    val region: kotlin.String,

    @Json(name = "city")
    val city: kotlin.String,

    @Json(name = "address")
    val address: kotlin.String,

    @Json(name = "latitude")
    val latitude: kotlin.Double,

    @Json(name = "longitude")
    val longitude: kotlin.Double,

    @Json(name = "postalCode")
    val postalCode: kotlin.String,

    @Json(name = "radius")
    val radius: kotlin.Double,

    @Json(name = "ui_id")
    val uiId: kotlin.String? = null

)

