/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.r3chain.core.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param googlePlaceID 
 * @param rawAddress 
 * @param id 
 * @param uiId 
 */


data class LocationSaveDto (

    @Json(name = "googlePlaceID")
    val googlePlaceID: kotlin.String,

    @Json(name = "rawAddress")
    val rawAddress: kotlin.String,

    @Json(name = "id")
    val id: kotlin.Int,

    @Json(name = "ui_id")
    val uiId: kotlin.String? = null

)

