/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.r3chain.core.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param name 
 * @param address1 
 * @param address2 
 * @param phone 
 * @param email 
 * @param website 
 * @param country 
 * @param city 
 * @param state 
 * @param zip 
 * @param imageResourceID 
 * @param uiId 
 */


data class OrganizationDto (

    @Json(name = "id")
    val id: kotlin.Int,

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "address1")
    val address1: kotlin.String,

    @Json(name = "address2")
    val address2: kotlin.String,

    @Json(name = "phone")
    val phone: kotlin.String,

    @Json(name = "email")
    val email: kotlin.String,

    @Json(name = "website")
    val website: kotlin.String,

    @Json(name = "country")
    val country: kotlin.String,

    @Json(name = "city")
    val city: kotlin.String,

    @Json(name = "state")
    val state: kotlin.String,

    @Json(name = "zip")
    val zip: kotlin.String,

    @Json(name = "imageResourceID")
    val imageResourceID: kotlin.Int,

    @Json(name = "ui_id")
    val uiId: kotlin.String? = null

)

