/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.r3chain.core.api.models

import io.r3chain.core.api.models.EnumPartnerType

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param partnerIDList 
 * @param partnerTypeList 
 */


data class PartnerListRequestDto (

    @Json(name = "partnerIDList")
    val partnerIDList: kotlin.collections.List<kotlin.Int>,

    @Json(name = "partnerTypeList")
    val partnerTypeList: kotlin.collections.List<EnumPartnerType>

)

