/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.r3chain.core.api.models

import io.r3chain.core.api.models.EnumPlasticType
import io.r3chain.core.api.models.PlasticWeightDto
import io.r3chain.core.api.models.TraceWasteRecordDto

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param tracePlasticType 
 * @param traceWasteRecordListDto 
 * @param weightDto 
 */


data class TraceWasteTypeRecordDto (

    @Json(name = "tracePlasticType")
    val tracePlasticType: EnumPlasticType? = null,

    @Json(name = "traceWasteRecordListDto")
    val traceWasteRecordListDto: kotlin.collections.List<TraceWasteRecordDto>? = null,

    @Json(name = "weightDto")
    val weightDto: PlasticWeightDto? = null

)

