/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.r3chain.core.api.models

import io.r3chain.core.api.models.ApiStatusCode
import io.r3chain.core.api.models.ErrorEntity
import io.r3chain.core.api.models.LocationDto
import io.r3chain.core.api.models.PartnerDto
import io.r3chain.core.api.models.PlasticWeightDto
import io.r3chain.core.api.models.ResourceDto
import io.r3chain.core.api.models.TraceStepDto
import io.r3chain.core.api.models.WasteRecordDto

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param statusCode 
 * @param message 
 * @param errorList 
 * @param responseResourceList 
 * @param traceStepList 
 * @param weightDto 
 * @param wasteRecordList 
 * @param partnerList 
 * @param locationList 
 */


data class TraceResponseEntity (

    @Json(name = "statusCode")
    val statusCode: ApiStatusCode? = null,

    @Json(name = "message")
    val message: kotlin.String? = null,

    @Json(name = "errorList")
    val errorList: kotlin.collections.List<ErrorEntity>? = null,

    @Json(name = "responseResourceList")
    val responseResourceList: kotlin.collections.Map<kotlin.String, ResourceDto>? = null,

    @Json(name = "traceStepList")
    val traceStepList: kotlin.collections.List<TraceStepDto>? = null,

    @Json(name = "weightDto")
    val weightDto: PlasticWeightDto? = null,

    @Json(name = "wasteRecordList")
    val wasteRecordList: kotlin.collections.Map<kotlin.String, WasteRecordDto>? = null,

    @Json(name = "partnerList")
    val partnerList: kotlin.collections.Map<kotlin.String, PartnerDto>? = null,

    @Json(name = "locationList")
    val locationList: kotlin.collections.Map<kotlin.String, LocationDto>? = null

)

